import { NextResponse } from 'next/server';
import { S3Client, GetObjectCommand } from '@aws-sdk/client-s3';

const s3 = new S3Client({
    region: 'us-east-1',
    credentials: {
        accessKeyId: process.env.AWS_ACCESS_KEY_ID || '',
        secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY || '',
    },
});

/**
 * GET /api/monthly
 * Fetches pre-computed monthly_stats.json from S3.
 * This file is generated by scripts/feature_engineering.py on the 1st of each month
 * and contains all aggregates needed by the Monthly Insights dashboard.
 */
export async function GET() {
    try {
        const bucket = process.env.AWS_S3_BUCKET;
        if (!bucket) {
            return NextResponse.json(
                { error: 'AWS_S3_BUCKET not configured' },
                { status: 500 }
            );
        }

        const command = new GetObjectCommand({
            Bucket: bucket,
            Key: 'citi_bike/monthly_stats.json',
        });

        const response = await s3.send(command);
        const bodyText = await response.Body.transformToString('utf-8');
        const stats = JSON.parse(bodyText);

        return NextResponse.json(stats);
    } catch (err) {
        // If monthly_stats.json doesn't exist on S3 yet, return helpful error
        if (err.name === 'NoSuchKey' || err.$metadata?.httpStatusCode === 404) {
            return NextResponse.json(
                {
                    error:
                        'Monthly data not yet available on S3. Run the Feature Engineering pipeline to generate it: uv run scripts/feature_engineering.py',
                },
                { status: 404 }
            );
        }

        console.error('Monthly API Error:', err);
        return NextResponse.json(
            { error: `Failed to load monthly stats: ${err.message}` },
            { status: 500 }
        );
    }
}
