channels:
- conda-forge
dependencies:
- python=3.10.16
- pip<=25.1
- pip:
  - mlflow==2.22.0
  - cffi==1.17.1
  - cloudpickle==3.1.1
  - defusedxml==0.7.1
  - lightgbm==4.6.0
  - matplotlib==3.10.3
  - numpy==1.26.4
  - pandas==2.1.4
  - psutil==5.9.0
  - pyarrow==19.0.1
  - scikit-learn==1.6.1
  - scipy==1.15.3
name: mlflow-env
