name: Feature Engineering

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 1 * *'  # Run at 5:00 AM UTC on the 1st of every month

jobs:
  feature_engineering:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: '3.12'

    - name: Run feature engineering
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      run: |
        uv run scripts/feature_engineering.py

    - name: Keep Runner Alive (S3 Upload)
      if: success()
      run: echo "Dataset successfully uploaded to S3."
